#!/usr/bin/env python

from argparse import ArgumentParser, ArgumentTypeError
from gus import GusFSAdapter
from watchdog.events import LoggingEventHandler, FileSystemEventHandler
from watchdog.observers import Observer
from wdeventhandler import WDEventHandler
import re
import time

parser = ArgumentParser(prog="gus", description="Generate static sites from textile and mustache files.")
def src_dest_argtype(string):
	match = re.match("(?P<src>[^:]+):(?P<dest>[^:]+)", string)
	if match is None:
		raise ArgumentTypeError("gus [--match] src_dir:dest_dir")
	return match.groupdict()

parser.add_argument("-w", "--watch", action="store_true", help="Watch src directory for changes.")
parser.add_argument("src_dest", metavar="src_dir:dest_dir", type=src_dest_argtype,
	help="The source and generated site are set using a colon. For example, gus src:public")

args = parser.parse_args()

gus = GusFSAdapter(args.src_dest['src'], args.src_dest['dest'])

gus.render_site()
if args.watch:
	print "Waiting on edits"
	event_handler = WDEventHandler(gus)
	observer = Observer()
	observer.schedule(event_handler, path=args.src_dest['src'], recursive=True)
	observer.start()
	try:
		while True:
			time.sleep(1)
	except KeyboardInterrupt:
		observer.stop()
	observer.join()
